version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/TwitterWallApp/
hooks:
  AfterInstall:
    - location: app-config.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: app-start.sh
      timeout: 3600
      runas: root
  ApplicationStop:
    - location: app-stop.sh
      timeout: 3600
      runas: root

